<a href="https://colab.research.google.com/github/Yiiize/MSSP6070/blob/main/WeeklyModules/Week05/Participation_Activity5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'Yiiize' # Replace with the GitHub repository owner
repository = 'MSSP6070' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP6070/MSSP6070

In [10]:
import pandas as pd
repository_dir = os.getcwd()
data_dir = os.path.join(repository_dir, 'data')

#b: read the file
filenames = ["aapl.csv", "amzn.csv", "fb.csv", "goog.csv", "nflx.csv"]
tickers = ["AAPL", "AMZN", "FB", "GOOG", "NFLX"]

dfs = {} # Dictionary to store dataframes

#c: add a ticker
for filename, ticker in zip(filenames, tickers):
    filepath = os.path.join(data_dir, filename)
    try:
        df = pd.read_csv(filepath)
        df['ticker'] = ticker
        dfs[ticker] = df # Store dataframe in dictionary
        print(f"DataFrame for {ticker}:")
        display(df.head())
    except FileNotFoundError:
        print(f"Error: The file {filepath} was not found.")

DataFrame for AAPL:

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

DataFrame for AMZN:

         date     open     high      low    close   volume ticker
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494   AMZN
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793   AMZN
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089   AMZN
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743   AMZN
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475   AMZN

DataFrame for FB:

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

DataFrame for GOOG:

         date     open     high      low    close   volume ticker
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564   GOOG
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170   GOOG
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605   GOOG
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123   GOOG
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603   GOOG

DataFrame for NFLX:

         date    open    high       low   close    volume ticker
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889   NFLX
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369   NFLX
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616   NFLX
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240   NFLX
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178   NFLX

In [11]:

# check dfs
if 'dfs' not in globals() or not dfs:
    raise ValueError("⚠️ 未找到 dfs，请先运行读取五个 CSV 的代码。")

#d: combine all DataFrame
faanf = pd.concat(dfs.values(), ignore_index=True)

# ensure the path
os.makedirs('data', exist_ok=True)

#e: save as csv doc
faanf.to_csv('data/faanf.csv', index=False)

print("✅ 已将 dfs 合并并保存为 data/faanf.csv")
print("文件行列数：", faanf.shape)

# see first rows
display(faanf.head())

✅ 已将 dfs 合并并保存为 data/faanf.csv
文件行列数： (1255, 7)

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [12]:

# f:read csv doc
df = pd.read_csv('data/faanf.csv')  # 如果文件名是 faanf.csv，请改成 'data/faanf.csv'

# colmns small letter
df.columns = [c.lower() for c in df.columns]

# change date to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')
if df['date'].isna().any():
    print(f"⚠️ {df['date'].isna().sum()} date(s) could not be parsed and are NaT")

# change volume to int
df['volume'] = df['volume'].astype(str).str.replace(',', '', regex=False)  # 移除逗号
df['volume'] = pd.to_numeric(df['volume'], errors='coerce').fillna(0).astype(int)

# ensure ticker exist and big letters
if 'ticker' not in df.columns:
    raise KeyError("Ticker column not found")
df['ticker'] = df['ticker'].astype(str).str.upper()

# sort date and ticker
df = df.sort_values(by=['date','ticker']).reset_index(drop=True)

# review first rows
print("✅ 数据类型和前几行：")
print(df.dtypes)
display(df.head())

# save as csv
df.to_csv('data/fanng_cleaned.csv', index=False)
print("✅ 已保存 cleaned CSV 为 data/fanng_cleaned.csv")

✅ 数据类型和前几行：
date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
2 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
3 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
4 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

✅ 已保存 cleaned CSV 为 data/fanng_cleaned.csv

In [13]:

# g: Find the seven rows with the highest volume
top7 = df.nlargest(7, 'volume')  # sorts descending by volume automatically
print("Top 7 rows by volume:")
display(top7)

# h: Melt the DataFrame
# Keep 'date' and 'ticker' as identifiers, melt all other columns
id_vars = ['date', 'ticker']
value_vars = [col for col in df.columns if col not in id_vars]

melted = pd.melt(df, id_vars=id_vars, value_vars=value_vars,
                 var_name='variable', value_name='value')

print("Melted DataFrame preview:")
display(melted.head())

Top 7 rows by volume:

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

Melted DataFrame preview:

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000